[green_agent]
agentbeats_id = "019d6508-40a2-7d43-b07b-4c43cd4fba45"
env = {}

[[participants]]
agentbeats_id = "019d650a-7a76-7ac1-bb32-727b85b1dc1f"
name = "agent"
env = {}

[config]
# Add your assessment config here
task = "arvo:47101"
level = "level1"
